#!/usr/bin/env python3
"""gen-authorizing-actions.py - the table of AWS operations authorized by differently named actions.

    python3 scripts/gen-authorizing-actions.py [CACHE_DIR]

Reads AWS's service reference (https://servicereference.us-east-1.amazonaws.com/), which
lists for every API operation the IAM actions that authorize it, and writes
crates/remit-reconcile/src/authorizing-actions.tsv: one line per operation whose actions
are not simply `service:Operation`. The reconciler checks an event against these actions
(SPEC section 6.5). Operations not in the file are authorized by the action of the same
name.

For each operation the file keeps the operation's own service's actions, since the others
AWS lists are conditional or legacy (`aws-portal:ViewBilling` beside `budgets:ViewBudget`);
an operation authorized only by another service's actions keeps those. An operation whose
own actions include its own name needs no line.

Downloads go to CACHE_DIR if given, so a rerun can reuse them. Standard library only.
"""

import concurrent.futures
import datetime
import json
import os
import sys
import tempfile
import urllib.request

INDEX = "https://servicereference.us-east-1.amazonaws.com/"
OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..", "crates", "remit-reconcile", "src", "authorizing-actions.tsv",
)


def fetch(url, path):
    if not os.path.exists(path):
        with urllib.request.urlopen(url, timeout=60) as r:
            data = r.read()
        with open(path, "wb") as f:
            f.write(data)
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main():
    cache = sys.argv[1] if len(sys.argv) > 1 else tempfile.mkdtemp(prefix="svcref-")
    os.makedirs(cache, exist_ok=True)
    index = fetch(INDEX, os.path.join(cache, "index.json"))

    def one(entry):
        return fetch(entry["url"], os.path.join(cache, entry["service"] + ".json"))

    with concurrent.futures.ThreadPoolExecutor(8) as pool:
        services = list(pool.map(one, index))

    rows = []
    for doc in services:
        service = doc["Name"]
        for op in doc.get("Operations") or []:
            listed = op.get("AuthorizedActions") or []
            if not listed:
                continue
            own = sorted({a["Name"] for a in listed if a["Service"] == service})
            if op["Name"] in own:
                continue
            actions = (
                [f"{service}:{a}" for a in own]
                if own
                else sorted({f"{a['Service']}:{a['Name']}" for a in listed})
            )
            rows.append((service, op["Name"], ",".join(actions)))
    rows.sort()

    today = datetime.date.today().isoformat()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(f"# Generated by scripts/gen-authorizing-actions.py from {INDEX} on {today}.\n")
        f.write("# Do not edit: rerun the script. service<TAB>operation<TAB>actions, any one of which authorizes it.\n")
        for row in rows:
            f.write("\t".join(row) + "\n")
    print(f"{len(rows)} operations from {len(services)} services -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
